name: Deploy
on:
  push:
    branches:
      - "tests"
      - "main" 
  pull_request:
    branches:
      - "**"
jobs:
  deploy:  
    env:
      enable-deploy: ${{ github.ref_name == 'tests' || (github.repository !=  'Sensedia/openapi' && github.ref_name == 'main')}}
    name: Deploy Github pages 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.repository }}
          echo ${{ github.ref_name }}
      - name: Deploy
        if: env.enable-deploy == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
      
